name: Library CI + SonarCloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      # 1) سحب الكود
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) إعداد JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) كاش للـ Maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4) بناء المشروع + التستات + JaCoCo
      - name: Build and run tests
        run: mvn -B clean verify

      # 5) كاش لـ SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 6) تشغيل تحليل SonarCloud مع JaCoCo
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # لازم تكون ضيفه بالSecrets
        run: >
          mvn -B jacoco:prepare-agent verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          jacoco:report
          -Dsonar.organization=abood-ja
          -Dsonar.projectKey=abood-ja_books_library
  
          -Dsonar.host.url=https://sonarcloud.io
